"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    os.environ.get(
        'SESSION_SECRET',
        'django-insecure-1r$7e=e96k6eq&7upd!li4s%%24(=f4x+r!va8nkg3dg2@!y(h',
    ),
)

# Hatayı ekranda net görebilmek için geçici olarak True yapıyoruz
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Replit preview/deployment proxies send the browser origin separately from
# the request host. Trust only the known Replit proxy suffixes plus explicitly
# configured domains so Django's CSRF middleware accepts same-app POSTs.
_configured_origins = []
for _domain in (
    os.environ.get('REPLIT_DEV_DOMAIN', ''),
    os.environ.get('REPLIT_DOMAINS', ''),
):
    for _value in _domain.split(','):
        _value = _value.strip().removeprefix('https://').removeprefix('http://').rstrip('/')
        if _value:
            _configured_origins.append(f'https://{_value}')

_extra_origins = [
    item.strip()
    for item in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if item.strip()
]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([
    'https://*.replit.dev',
    'https://*.replit.app',
    'https://*.repl.co',
    'http://localhost:5000',
    'http://127.0.0.1:5000',
    *_configured_origins,
    *_extra_origins,
]))
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Database
# Replit's persistent PostgreSQL database is preferred when DATABASE_URL is
# available. SQLite remains a local fallback for environments without it.
database_url = os.environ.get('DATABASE_URL', '').strip()
if database_url:
    parsed_database_url = urlparse(database_url)
    database_options = {
        key: values[-1]
        for key, values in parse_qs(parsed_database_url.query).items()
        if values
    }
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote(parsed_database_url.path.lstrip('/')),
            'USER': unquote(parsed_database_url.username or ''),
            'PASSWORD': unquote(parsed_database_url.password or ''),
            'HOST': parsed_database_url.hostname or '',
            'PORT': str(parsed_database_url.port or ''),
            'OPTIONS': database_options,
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
]


# Internationalization (Türkçe Dil ve Saat Ayarları)
LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Yönlendirme ve Giriş Ayarları
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'
SESSION_COOKIE_AGE = 2592000
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Session ve CSRF Ayarları
SESSION_COOKIE_SECURE = False  # HTTP için False, HTTPS için True olmalı
SESSION_COOKIE_HTTPONLY = True  # XSS koruması için
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF koruması için
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 gün
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Tarayıcı kapanınca session silinmez

CSRF_COOKIE_SECURE = False  # HTTP için False, HTTPS için True olmalı
CSRF_COOKIE_HTTPONLY = True  # XSS koruması için
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF koruması için
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')